Repository quac88/NitDestroyer, pull requests merged in 2023-10, with the labels that each got.

#1 docs: create rules for contributing.md
  contributing.md
Labels: documentation

#13 feat: add type annotations for pot params and dealer param in game class
  src/poker/game.py
Labels: enhancement

#22 Quac/feat/improve run.py
  requirements.txt
  src/poker/cardecky.py
  src/poker/game.py
  src/poker/run.py
Labels: help wanted
